//
//     Generated by AnV Software
//
//  Copyright © 2019 Andy Vandijck.
//

#import "AppDelegate.h"

@implementation AppDelegate
- (void)applicationDidFinishLaunching:(id)unused
{
    [[NSBundle mainBundle] 
}
@end
