//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  2 2019 07:17:21).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#ifndef NIBUNLOCKER_APPDELEGATE_H
#define NIBUNLOCKER_APPDELEGATE_H

#import <Foundation/NSObject.h>
#import <Foundation/NSBundle.h>
#import <AppKit/NSApplication.h>

#ifndef VISIBILITY_HIDDEN
#define VISIBILITY_HIDDEN __attribute__((visibility("hidden")))
#endif /* VISIBILITY_HIDDEN */

VISIBILITY_HIDDEN
@interface AppDelegate : NSObject <NSApplicationDelegate>
{
}

- (void)applicationDidFinishLaunching:(id)arg1;

@end

#endif /* NIBUNLOCKER_APPDELEGATE_H */
